// Products
export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

// Cart
export const FETCH_CARTS_LOADING = "FETCH_CARTS_LOADING";
export const FETCH_CARTS = "FETCH_CARTS";
export const FETCH_CARTS_FAILURE = "FETCH_CARTS_FAILURE";
export const INSERT_CART_LOADING = "INSERT_CART_LOADING";
export const INSERT_CART = "INSERT_CART";
export const INSERT_CART_FAILURE = "INSERT_CART_FAILURE";
export const UPDATE_CART_LOADING = "UPDATE_CART_LOADING";


